### ISSUE TITLE
[enhancement] delete function in Brower Plugin

### ISSUE THREAD

**Issue by glorang** [1afa/sambadav#11]
Hello,

I've added a delete function in the SambaDAV Browser Plugin in https://github.com/glorang/sambadav/commit/06e20c803a36553f257d5f2c48595128bf2c433e

but I'm not sure if this is really the best way to do it. I had to copy over the complete httpPOST() method just to cope with the "del" case. 

Any thoughts on this? if you think this is worth the merge just let me know.

Thx;
Geert

**Comment by rdevroede** [comment]
Hi Geert,

The idea is great, but I don't like the entire copy of httpPOST(). Why not extend initialize() in stead and hook another POST listener?

Something like this (quick concept on an older version, but the idea is the same):

--- webfolders.orig/lib/SambaDAV/BrowserPlugin.php	2014-09-22 12:25:56.000000000 +0200
+++ webfolders/lib/SambaDAV/BrowserPlugin.php	2015-09-04 16:29:00.000000000 +0200
@@ -23,6 +23,51 @@
 
 class BrowserPlugin extends DAV\Browser\Plugin
 {
+    public function initialize(DAV\Server $server) {
+	parent::initialize($server);
+        if ($this->enablePost) $this->server->subscribeEvent('unknownMethod',array($this,'httpPOSTExtra'));
+    }
+
+    	/**
+    	 * Handles POST requests for tree operations not handled in the SabreDAV parent class
+    	 *
+    	 * @param RequestInterface $request
+    	 * @param ResponseInterface $response
+    	 * @return bool
+    	 */
+    public function httpPOSTExtra($method, $uri) {
+
+        if ($method!='POST') return;
+        $contentType = $this->server->httpRequest->getHeader('Content-Type');
+        list($contentType) = explode(';', $contentType);
+        if ($contentType !== 'application/x-www-form-urlencoded' &&
+            $contentType !== 'multipart/form-data') {
+                return;
+        }
+        $postVars = $this->server->httpRequest->getPostVars();
+
+        if (!isset($postVars['sabreActionExtra']))
+            return;
+
+        if ($this->server->broadcastEvent('onBrowserPostAction', array($uri, $postVars['sabreActionExtra'], $postVars))) {
+
+            switch($postVars['sabreActionExtra']) {
+    	    	    case 'del':
+    	                if (isset($postVars['path'])) {
+				// Using basename() because we won't allow slashes
+				list(, $Name) = DAV\URLUtil::splitPath(trim($postVars['path']));
+    	    			$this->server->tree->delete($uri . '/' . $Name);
+    	    	    	}
+    	    	    	break;
+    	        }
+
+    	    }
+        $this->server->httpResponse->setHeader('Location',$this->server->httpRequest->getUri());
+        $this->server->httpResponse->sendStatus(302);
+    	return false;
+
+    }
+
 	public function
 	generateDirectoryIndex ($path)
 	{
@@ -68,7 +113,9 @@
         <col/>
       </colgroup>
       <thead>
-        <tr><th></th><th>Name</th><th>Type</th><th>Size</th><th>Last modified</th></tr>
+        <tr><th></th><th>Name</th><th>Type</th><th>Size</th><th>Last modified</th>
+	<th>Delete</th>
+</tr>
       </thead>
       <tbody>";
 
@@ -92,6 +139,7 @@
     <td>[parent]</td>
     <td></td>
     <td></td>
+    <td></td>
     </tr>";
 
 		}
@@ -157,8 +205,15 @@
     <td><a href=\"{$fullPath}\">{$displayName}</a></td>
     <td>{$type}</td>
     <td>{$size}</td>
-    <td>{$lastmodified}</td>
-    </tr>";
+    <td>{$lastmodified}</td>";
+$html .= "          <td>\n";
+				$html .= "          <form method=\"post\" enctype=\"multipart/form-data\" onsubmit=\"return confirm('Are you sure you want to delete \'" . $displayName . "\'');\">\n";
+				$html .= "          <input name=\"sabreActionExtra\" value=\"del\" type=\"hidden\">\n";
+				$html .= "          <input name=\"path\" value=\"{$fullPath}\" type=\"hidden\">\n";
+				$html .= "          <input value=\"Delete\" type=\"submit\">\n";
+				$html .= "          </form>\n";
+				$html .= "          </td>\n";
+    $html .= "</tr>";
 
 		}
 		$html .=

If you can get something like that working, I would be happy to merge the change. It's probably a good idea to make this feature configurable and turned off by default.

Best regards,
Richard de Vroede
1A First Alternative

**Comment by rdevroede** [comment]
This feature has been merged.
